version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 20
    cooldown:
      default-days: 3
      semver-major-days: 7
      semver-minor-days: 5
      semver-patch-days: 3
    schedule:
      interval: "daily"
      time: "04:12"
      timezone: "Europe/London"
    rebase-strategy: disabled
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps(java): "

  - package-ecosystem: "github-actions"
    directory: "/"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps(actions): "
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "05:13"
      timezone: Europe/London
    rebase-strategy: disabled
    cooldown:
      default-days: 3
      exclude:
        - "quotidian-ennui/*"
    groups:
      workflows-olio:
        patterns:
          - "quotidian-ennui/workflows-olio/*"

  - package-ecosystem: "docker"
    directory: "src/main/docker"
    open-pull-requests-limit: 20
    rebase-strategy: disabled
    cooldown:
      default-days: 3
    schedule:
      interval: "daily"
      time: "04:17"
      timezone: "Europe/London"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps(docker-image): "
