version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps(java): "

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps(ci): "
