version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 50
    schedule:
      interval: "daily"
    versioning-strategy: increase
    allow:
      - dependency-type: "all"
    groups:
      # It does seem to me that trying to make npm dependencies
      # play nice with each other is a fool's errand.  I'm going
      # just hopefully use dependency-type to group all the
      # transitive deps from running eslint into a single thing
      dev-dependencies:
        dependency-type: "development"
      winston:
        patterns:
          - "winston"
          - "winston-*"
      axios:
        patterns:
          - "axios"
          - "axios-*"
          - "retry-axios"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps(ci): "
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(docker): "
