version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 20
    cooldown:
      default-days: 3
      semver-major-days: 7
      semver-minor-days: 5
      semver-patch-days: 3
    schedule:
      interval: "daily"
      time: "04:12"
      timezone: "Europe/London"
    rebase-strategy: disabled
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps(java): "

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
      time: "04:17"
      timezone: "Europe/London"
    rebase-strategy: disabled
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps(ci): "
    groups:
      workflows-olio:
        patterns:
          - "quotidian-ennui/workflows-olio/*"
