version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    versioning-strategy: increase
    allow:
      - dependency-type: "all"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
