version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    versioning-strategy: increase
    allow:
      - dependency-type: "all"
    groups:
      eslint:
        patterns:
          - "eslint*"
          - "eslint"
          - "es-abstract"
          - "es-abstract*"
          - "es-*"
          - "@eslint*"
          - "@eslint/*"
      babel:
        patterns:
          - "@babel*"
          - "@babel/*"
      types:
        patterns:
          - "@types*"
          - "@types/*"
      prototype:
        patterns:
          - "string.prototype"
          - "string.prototype*"
          - "iterator.prototype"
          - "iterator.prototype*"
          - "arraybuffer.prototype"
          - "arraybuffer.prototype.*"
          - "array.prototype"
          - "array.prototype.*"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps(ci): "
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(docker): "
