quarkus:
  http:
    port: ${QUARKUS_HTTP_PORT:9961}
  ssl:
    native: true
  log:
    level: INFO
    category:
      "io.github.qe":
        level: ${LOG_LEVEL:INFO}
  micrometer:
    export:
      prometheus:
        enabled: true
        path: /metrics
    binder:
      jvm: false
      system: false
      http-client:
        enabled: false
      http-server:
        enabled: false
      netty:
        enabled: false
      vertx:
        enabled: false
      mp-metrics:
        enabled: false

powerwall:
  scrape:
    interval: ${SCRAPE_INTERVAL:60s}

"%dev":
  quarkus:
    log:
      level: ${LOG_LEVEL:INFO}
      category:
        "io.github.qe":
          level: DEBUG
  micrometer:
    binder:
      jvm: true
  powerwall:
    scrape:
      interval: 20s