####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
# It uses a micro base image, tuned for Quarkus native executables.
# It reduces the size of the resulting container image.
# Check https://quarkus.io/guides/quarkus-runtime-base-image for further information about this image.
#
# Before building the container image run:
#
# ./gradlew build -Dquarkus.package.type=native
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native-micro -t quarkus/tesla .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/tesla
#
###
FROM quay.io/quarkus/ubi10-quarkus-micro-image:2.0-2026-09-13@sha256:fab12409e9425f60167ba417a0e0d1bd7c0cc8884880e526e10652a6cc366a49
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
EXPOSE 8080
USER 1001

COPY --chown=1001:root build/*-runner /work/application

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
