####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
# It uses a micro base image, tuned for Quarkus native executables.
# It reduces the size of the resulting container image.
# Check https://quarkus.io/guides/quarkus-runtime-base-image for further information about this image.
#
# Before building the container image run:
#
# ./gradlew build -Dquarkus.package.type=native
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native-micro -t quarkus/tesla .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/tesla
#
###
FROM quay.io/quarkus/ubi10-quarkus-micro-image:2.0-2026-08-09@sha256:240436530171f92c462e4c0882179920c7d7788996907ce4fc30464ab0c69ef5
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
EXPOSE 8080
USER 1001

COPY --chown=1001:root build/*-runner /work/application

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
