name: build
run-name: Build PR (${{ github.event.client_payload.detail.pull_request }})
on:
  repository_dispatch:
    types:
      - dependency-review-success

env:
  STATUS_CONTEXT: "Gradle Check"
  LABEL_PREFIX: "build_"

permissions: {}

jobs:
  gradle:
    runs-on: ubuntu-latest
    name: Gradle Check
    permissions:
      contents: write
      pull-requests: write
      issues: write
      statuses: write
    steps:
      - name: Build Pending
        uses: quotidian-ennui/actions-olio/commit-status-and-label@83871db203c510c8c8d65292f24ebf5437728e7c # v0.9.1
        if: |
          github.event.client_payload.detail.pull_request != '' &&
          github.event.client_payload.base.sha != ''
        with:
          state: pending
          sha: ${{ github.event.client_payload.base.sha }}
          context: ${{ env.STATUS_CONTEXT }}
          label_prefix: ${{ env.LABEL_PREFIX }}
      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.client_payload.base.ref }}
          fetch-depth: 0
          persist-credentials: false
      - name: Setup java
        uses: quotidian-ennui/actions-olio/setup-java-gradle@80eb94186f07a299ea6a6954d56ee20926db1cd7 # v0.10.1
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Gradle
        id: gradle
        run: |
          ./gradlew -PdisableSpotlessJava=false check
      - name: Build Result
        if: |
          (success() || failure()) &&
          github.event.client_payload.detail.pull_request != '' &&
          github.event.client_payload.base.sha != ''
        uses: quotidian-ennui/actions-olio/commit-status-and-label@83871db203c510c8c8d65292f24ebf5437728e7c # v0.9.1
        with:
          state: ${{ steps.gradle.outcome }}
          sha: ${{ github.event.client_payload.base.sha }}
          context: ${{ env.STATUS_CONTEXT }}
          label_prefix: ${{ env.LABEL_PREFIX }}

  dependabot_merge:
    runs-on: ubuntu-latest
    name: Dependabot Merge
    permissions:
      contents: write
      pull-requests: write
    needs:
      - gradle
    steps:
      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.client_payload.base.ref }}
          persist-credentials: false
      - name: "Create Token"
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: app-token
        with:
          app-id: ${{ vars.WORKFLOW_UPDATE_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_UPDATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "${{ github.event.repository.name}}"
      - name: Repository Action Merge
        id: action_merge
        uses: quotidian-ennui/actions-olio/dependabot-merge@83871db203c510c8c8d65292f24ebf5437728e7c # v0.9.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          change_filter: ".github/workflows/**"
          merge_commentary: "Merge Workflow Actions"
      - name: Dependabot Merge
        id: merge_gradle_dependencies
        uses: quotidian-ennui/actions-olio/dependabot-merge@83871db203c510c8c8d65292f24ebf5437728e7c # v0.9.1
        with:
          token: ${{ steps.app-token.outputs.token }}
          change_filter: "**/build.gradle,**/build.gradle.kts"
          automerge_level: "semver-patch"
          merge_commentary: "Merge Gradle Dependencies"
          filter_separator: ","
          merge_retry_wait_seconds: 120
