name: build
run-name: Build PR (${{ github.event.client_payload.detail.pull_request }})
on:
  repository_dispatch:
    types:
      - dependency-review-success

env:
  STATUS_CONTEXT: "Gradle Check"
  LABEL_PREFIX: "build_"

permissions: {}

jobs:
  gradle:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Gradle Check
    permissions:
      contents: write
      pull-requests: write
      issues: write
      statuses: write
    steps:
      - name: Build Pending
        uses: quotidian-ennui/actions-olio/commit-status-and-label@448a2329caa783bbfe2ad58fc2123f7e05efae89 # v0.10.3
        if: |
          github.event.client_payload.detail.pull_request != '' &&
          github.event.client_payload.base.sha != ''
        with:
          state: pending
          sha: ${{ github.event.client_payload.base.sha }}
          context: ${{ env.STATUS_CONTEXT }}
          label_prefix: ${{ env.LABEL_PREFIX }}
      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.client_payload.base.ref }}
          fetch-depth: 0
          persist-credentials: false
      - name: Setup java
        uses: quotidian-ennui/actions-olio/setup-java-gradle@448a2329caa783bbfe2ad58fc2123f7e05efae89 # v0.10.3
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Gradle
        id: gradle
        run: |
          ./gradlew -PdisableSpotlessJava=false check
      - name: Build Result
        if: |
          (success() || failure()) &&
          github.event.client_payload.detail.pull_request != '' &&
          github.event.client_payload.base.sha != ''
        uses: quotidian-ennui/actions-olio/commit-status-and-label@448a2329caa783bbfe2ad58fc2123f7e05efae89 # v0.10.3
        with:
          state: ${{ steps.gradle.outcome }}
          sha: ${{ github.event.client_payload.base.sha }}
          context: ${{ env.STATUS_CONTEXT }}
          label_prefix: ${{ env.LABEL_PREFIX }}

  dependabot_merge:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    name: Dependabot Merge
    needs:
      - gradle
    steps:
      - name: "Create Token"
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          client-id: ${{ vars.WORKFLOW_UPDATE_CLIENT_ID }}
          private-key: ${{ secrets.WORKFLOW_UPDATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "${{ github.event.repository.name}}"
          permission-contents: write
          permission-pull-requests: write
          permission-workflows: write
      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.client_payload.base.ref }}
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
      - name: Repository Action Merge
        id: action_merge
        uses: quotidian-ennui/actions-olio/dependabot-merge@448a2329caa783bbfe2ad58fc2123f7e05efae89 # v0.10.3
        with:
          token: ${{ steps.app-token.outputs.token }}
          change_filter: ".github/workflows/**"
          merge_commentary: "Merge Workflow Actions"
      - name: Dependabot Merge
        id: merge_gradle_dependencies
        uses: quotidian-ennui/actions-olio/dependabot-merge@448a2329caa783bbfe2ad58fc2123f7e05efae89 # v0.10.3
        with:
          token: ${{ steps.app-token.outputs.token }}
          change_filter: "**/build.gradle,**/build.gradle.kts"
          automerge_level: "semver-patch"
          merge_commentary: "Merge Gradle Dependencies"
          filter_separator: ","
          merge_retry_wait_seconds: 120
