name: dependency-review
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  dependency-review:
    timeout-minutes: 2
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: "Dependency Review"
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          comment-summary-in-pr: true
          vulnerability-check: true
          license-check: true
          fail-on-severity: moderate
          allow-dependencies-licenses: "pkg:githubactions/quotidian-ennui/actions-olio/pr-trigger, pkg:githubactions/quotidian-ennui/actions-olio/docker-image-builder"

  review-success:
    timeout-minutes: 1
    needs:
      - dependency-review
    permissions:
      contents: write
      pull-requests: read
      issues: read
    runs-on: ubuntu-latest
    name: Dispatch
    steps:
      - name: dispatch
        uses: quotidian-ennui/actions-olio/pr-trigger@528d118cf867515584403396edee8a564a23bc00 # v1.3.0
        with:
          event_type: dependency-review-success
