name: dependabot-pr
run-name: Merge Dependabot PR (${{ github.event.client_payload.detail.pull_request }})
on:
  repository_dispatch:
    types:
      - pr-trigger

env:
  STATUS_CONTEXT: "Gradle Check"
  LABEL_PREFIX: "build_"
permissions:
  contents: write
  pull-requests: write
  issues: write
  statuses: write

jobs:
  gradle:
    runs-on: ubuntu-latest
    name: Gradle Check
    steps:
      - name: Build Pending
        uses: quotidian-ennui/actions-olio/commit-status-and-label@main
        if: |
          github.event.client_payload.detail.pull_request != '' &&
          github.event.client_payload.base.sha != ''
        with:
          state: pending
          sha: ${{ github.event.client_payload.base.sha }}
          context: ${{ env.STATUS_CONTEXT }}
          label_prefix: ${{ env.LABEL_PREFIX }}
      - name: Checkout branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.event.client_payload.base.ref }}
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          java-version: 21
          distribution: "temurin"
      - name: Setup Gradle
        id: setup_gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
        with:
          gradle-version: wrapper
      - name: Gradle
        id: gradle
        env:
          JDK_JAVA_OPTIONS: -Dpolyglot.js.nashorn-compat=true -Dpolyglot.engine.WarnInterpreterOnly=false
        run: |
          ./gradlew check
      - name: Build Result
        if: |
          (success() || failure()) &&
          github.event.client_payload.detail.pull_request != '' &&
          github.event.client_payload.base.sha != ''
        uses: quotidian-ennui/actions-olio/commit-status-and-label@main
        with:
          state: ${{ steps.gradle.outcome }}
          sha: ${{ github.event.client_payload.base.sha }}
          context: ${{ env.STATUS_CONTEXT }}
          label_prefix: ${{ env.LABEL_PREFIX }}
  actions_merge:
    runs-on: ubuntu-latest
    name: Dependabot Merge (action changes)
    needs:
      - gradle
    steps:
      - name: Checkout branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.event.client_payload.base.ref }}
      - name: "Create Token"
        uses: actions/create-github-app-token@f4c6bf6752984b3a29fcc135a5e70eb792c40c6b # v1.8.0
        id: app-token
        with:
          app-id: ${{ vars.WORKFLOW_UPDATE_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_UPDATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Dependabot Merge
        id: dependabot_merge
        uses: quotidian-ennui/actions-olio/dependabot-merge@main
        with:
          token: ${{ steps.app-token.outputs.token }}
          change_filter: ".github/workflows/**"
