name: docker-latest
run-name: Build & Publish Docker Image

on:
  push:
    tags:
      - "*"
  repository_dispatch:
    types:
      - push-trigger
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/docker-image.yml
