name: docker-latest

on:
  push:
    branches:
      - master
      - quarkus
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: ./.github/workflows/docker-image.yml
