name: docker-latest
run-name: Build & Publish Docker Image

on:
  push:
    tags:
      - "*"
  repository_dispatch:
    types:
      - push-trigger
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    uses: ./.github/workflows/docker-image.yml
