name: push-trigger
run-name: Push Build Trigger
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  repo-dispatch:
    timeout-minutes: 2
    permissions:
      contents: write
      pull-requests: read
      issues: read
    runs-on: ubuntu-latest
    name: Dispatch
    steps:
      - name: dispatch
        uses: quotidian-ennui/actions-olio/pr-trigger@7ee535611789442d6fa202dc02a19c81bf2c4458 # v0.10.4
        with:
          event_type: push-trigger
