name: create-release
on:
  push:
    tags:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  create-release:
    uses: quotidian-ennui/workflows-olio/.github/workflows/create-release.yml@fedb5906a58adee0925976d73e202d4c75ec2a45 # v2.2.1
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
